name = "All of CC Tweaked"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5950bae1743e0f571c313da9e6987c71e09f838c5fdc9fa53c5aced0339cb6e4"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
