name = "All of CC Tweaked"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd4f8fa40f2848d60f31e28e0e2e4dc3826931c3db26182a640c7aea0c9a2e1c"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
