name = "All of CC Tweaked"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0488432923ab61b456752121509f5da1f5d84309323d54c7c3e64f8029cb6a96"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
